name: Release Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance


jobs:
  release-please:
    name: version-changelog
    runs-on: ubuntu-latest
    outputs:
        tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: dart
          package-name: release-please-action
  publish_flutter_arm64_macos:
    needs: release-please
    name: publish_flutter_arm64_macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: arm64
      - run: |
          flutter config --enable-macos-desktop
          make build-client-macOS
          gh release upload ${{ needs.release-please.outputs.tag }} ./packaging/dmg/untitled2_arm64.dmg TAG=${{ needs.release-please.outputs.tag }}
      # 搭建flutter环境
      # - id: step3
      #   run: |
      #     echo "cat version.txt"
      #     ls
      #     cat version.txt
      # - id: step3
      #   run: |
      #     sudo apt-get update -y && sudo apt-get install jq -y
      #     version=$(jq -r '.version' package.json)
      #     echo "version=${version}" >> $GITHUB_OUTPUT
  # handle-pubspec:
  #   needs: release-please
  #   name: handle-pubspec
  #   runs-on: ubuntu-latest
  #   steps:
  #     # 检出代码到工作目录，直接进入项目的一级目录
  #     - id: step1
  #       name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - id: step2
  #       name: Update pubspec.yaml
  #       run: |
  #         ls
  #         pwd
  #         version=${{ needs.release-please.outputs.version }}
  #         sed -i "s/version: .*/version: ${version}/" pubspec.yaml
  #     - name: Commit and Push Changes
  #       run: |
  #         git config --global user.name "imagineboom"
  #         git config --global user.email "imagineboom@foxmail.com"
  #         git add pubspec.yaml
  #         git commit -m "build: update version in pubspec.yaml"
  #         git push