name: Release Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

# env:
#   flutter_version: '3.13.6'



jobs:
  release-please:
    name: version-changelog
    runs-on: ubuntu-latest
    outputs:
        tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: dart
          package-name: release-please-action
      - if: ${{ steps.release.outputs.release_created }}
        run: echo tag=${{ steps.release.outputs.tag_name }}
  publish_flutter_arm64_macos:
    needs: release-please
    if: ${{ needs.release-please.outputs.tag }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: ${{ env.flutter_version }}
          # architecture: arm64
      # - run: flutter doctor
      - run: ls
      - run: rm -rf ./node_modules
      - run: npm -v
      - run: npx -v
      - run: npm install
      - run: flutter config --enable-macos-desktop
      - run: npm install
      - run: make build-client-macOS
      - run: gh release upload ${{ needs.release-please.outputs.tag }} ./packaging/dmg/untitled2_arm64.dmg TAG=${{ needs.release-please.outputs.tag }}
