name: Release Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance


jobs:
  release-please:
    name: version-changelog
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step2.outputs.version }}
    steps:
      - id: step1
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
      - id: step2
        run: |
          version=$(echo "$json_data" | jq -r '.version')
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "version=${version}"
  handle-pubspec:
    needs: release-please
    name: handle-pubspec
    runs-on: ubuntu-latest
    steps:
      - run: |
          version=${{ needs.release-please.outputs.version }}
          echo pwd=$PWD
          sed -i "s/version: .*/version: ${version}/" pubspec.yaml
