name: Release Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance


jobs:
  release-please:
    name: version-changelog
    runs-on: ubuntu-latest
    outputs:
        tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: dart
          package-name: release-please-action
      - run: |
          echo fir=${{ steps.release.outputs.tag_name }}
  publish_flutter_arm64_macos:
    needs: release-please
    name: publish_flutter_arm64_macos
    runs-on: macos-latest
    steps:
      - run: |
          echo fir=${{ needs.release-please.outputs.tag }}
      # - uses: actions/checkout@v4
      # - uses: subosito/flutter-action@v2
      #   with:
      #     channel: 'stable'
      #     architecture: arm64
      # - run: |
      #     flutter config --enable-macos-desktop
      #     make build-client-macOS
      #     gh release upload ${{ needs.release-please.outputs.tag }} ./packaging/dmg/untitled2_arm64.dmg TAG=${{ needs.release-please.outputs.tag }}
