name: Release Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance
  packages: write
# env:
#   flutter_version: '3.13.6'

jobs:
  release-please:
    name: version-changelog
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: dart
          package-name: release-please-action
          include-v-in-tag: true
      - if: ${{ steps.release.outputs.release_created }}
        run:
          print("tag=${{ steps.release.outputs.tag_name }}")
        shell: python
  publish_flutter_x64_macos:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    env:
      TAG: ${{ needs.release-please.outputs.tag }}
      PRJ_NAME: "BoxInspector"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: ${{ env.flutter_version }}
          # architecture: arm64
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
      # - run: flutter doctor
      - run: ls
      - run: rm -rf ./node_modules
      - run: npm -v
      - run: npm install
      - run: flutter config --enable-macos-desktop
      - run: npm install
      - run: make build-client-macOS-x64 PRJ_NAME=${{ env.PRJ_NAME }} TAG=${{ env.TAG }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload v${{ env.TAG }} ./dist/${{ env.TAG }}/${{ env.PRJ_NAME }}-${{ env.TAG }}-x64.dmg --clobber
      - run: |
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
        shell: bash

  publish_flutter_x64_ubuntu:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    env:
      TAG: ${{ needs.release-please.outputs.tag }}
      PRJ_NAME: "BoxInspector"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: ${{ env.flutter_version }}
          # architecture: arm64
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
      # - run: flutter doctor
      - run: ls
      - run: sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      - run: flutter config --enable-linux-desktop
      - run: make build-client-ubuntu-x64 PRJ_NAME=${{ env.PRJ_NAME }} TAG=${{ env.TAG }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload v${{ env.TAG }} ./dist/${{ env.TAG }}/${{ env.PRJ_NAME }}-${{ env.TAG }}-x64.deb --clobber
      - run: |
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
        shell: bash

  publish_flutter_x64_windows:
    name: publish_flutter_x64_windows
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created  }}
    env:
      TAG: ${{ needs.release-please.outputs.tag }}
      PRJ_NAME: "BoxInspector"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: ${{ env.flutter_version }}
          # architecture: arm64
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
      # - run: flutter doctor
      - run: flutter config --enable-windows-desktop
      - uses: pwall2222/inno-setup-download@v0.0.4
      - run: rm -rf build/windows/
        shell: bash
      - run: rm -rf windows/
        shell: bash
      - run: flutter create --platform=windows .
        shell: bash
      - run: cp assets/images/box-icon2/icon.iconset/box-icon2.ico windows/runner/resources/app_icon.ico
        shell: bash
      - run: flutter build windows
        shell: bash
      - name: Inno Setup use Action
        uses: Minionguyjpro/Inno-Setup-Action@v1.0.0
        with:
          path: packaging/exe/InnoSteupScript.iss
          # options: /DMyAppName=${{ env.PRJ_NAME }} /DMyAppExeName="${{ env.PRJ_NAME }}-${{ env.TAG }}-x64.exe" /DMyAppVersion=${{ env.TAG }} /DDepDir="build\windows\runner\Release" /Qp /O"dist\${{ env.TAG }}" /F"${{ env.PRJ_NAME }}" /Sbyparam=$p "packaging\exe\InnoSteupScript.iss"
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload v${{ env.TAG }} dist/${{ env.TAG }}/${{ env.PRJ_NAME }}-${{ env.TAG }}-x64.exe
        shell: bash
      - run: |
          echo CACHE-PATH=${{ steps.flutter-action.outputs.CACHE-PATH }}
          echo CACHE-KEY=${{ steps.flutter-action.outputs.CACHE-KEY }}
          echo CHANNEL=${{ steps.flutter-action.outputs.CHANNEL }}
          echo VERSION=${{ steps.flutter-action.outputs.VERSION }}
          echo ARCHITECTURE=${{ steps.flutter-action.outputs.ARCHITECTURE }}
        shell: bash
